/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Create a new site
 */
export const createSiteBody = zod.object({
  "templateID": zod.number(),
  "planID": zod.number(),
  "userID": zod.string().uuid(),
  "fields": zod.record(zod.string(), zod.any()).optional().describe('json object with all widgets and fields of a site')
})

/**
 * @summary Update an existing site
 */
export const updateSiteParams = zod.object({
  "id": zod.number()
})

export const updateSiteBody = zod.object({
  "templateID": zod.number(),
  "domainType": zod.enum(['DefaultDomain', 'SeparateDomain', 'BringYourDomain']).optional(),
  "domain": zod.string().optional(),
  "newStatus": zod.enum(['InCreation', 'AwaitingProvision', 'Created']).optional(),
  "fields": zod.record(zod.string(), zod.any()).optional()
})

export const updateSiteResponse = zod.object({
  "siteID": zod.number()
})

/**
 * @summary Get info about an existing site
 */
export const getSiteParams = zod.object({
  "id": zod.number()
})

export const getSiteResponse = zod.object({
  "healthCheckStatus": zod.enum(['Healthy', 'Unhealthy', 'NotProvisioned']),
  "createdAt": zod.string()
})

