/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateSiteRequest,
  CreateSiteResponse,
  GetSiteResponse,
  UpdateSiteRequest,
  UpdateSiteResponse
} from '.././model';




  /**
 * @summary Create a new site
 */
export const createSite = <TData = AxiosResponse<CreateSiteResponse>>(
    createSiteRequest: CreateSiteRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/sites`,
      createSiteRequest,options
    );
  }
/**
 * @summary Update an existing site
 */
export const updateSite = <TData = AxiosResponse<UpdateSiteResponse>>(
    id: number,
    updateSiteRequest: UpdateSiteRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/sites/${id}`,
      updateSiteRequest,options
    );
  }
/**
 * @summary Get info about an existing site
 */
export const getSite = <TData = AxiosResponse<GetSiteResponse>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/sites/${id}`,options
    );
  }
export type CreateSiteResult = AxiosResponse<CreateSiteResponse>
export type UpdateSiteResult = AxiosResponse<UpdateSiteResponse>
export type GetSiteResult = AxiosResponse<GetSiteResponse>
