/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTemplateRequestFields } from "./createTemplateRequestFields";

export interface CreateTemplateRequest {
  /** template's name */
  name: string;
  /** json object with all widgets and fields of a site */
  fields: CreateTemplateRequestFields;
}
