/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePaymentResponse {
  clientSecret?: string;
  subscriptionID?: string;
}
