/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import type { FileUploadBodyMetadata } from "./fileUploadBodyMetadata";

export type FileUploadBody = {
  file?: Blob;
  /** json object with file metadata */
  metadata?: FileUploadBodyMetadata;
};
