/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */

export type GetSiteResponseHealthCheckStatus = typeof GetSiteResponseHealthCheckStatus[keyof typeof GetSiteResponseHealthCheckStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSiteResponseHealthCheckStatus = {
  Healthy: 'Healthy',
  Unhealthy: 'Unhealthy',
  NotProvisioned: 'NotProvisioned',
} as const;
