/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */

export interface TemplateInfo {
  id: number;
  templateName: string;
  /** url to pages.json file */
  structure: string;
  /** url to css file */
  styles: string;
  /** url to site's html for preview */
  preview: string;
}
