/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateSiteRequestDomainType } from './updateSiteRequestDomainType';
import type { UpdateSiteRequestNewStatus } from './updateSiteRequestNewStatus';
import type { UpdateSiteRequestFields } from './updateSiteRequestFields';

export interface UpdateSiteRequest {
  templateID: number;
  domainType?: UpdateSiteRequestDomainType;
  domain?: string;
  newStatus?: UpdateSiteRequestNewStatus;
  fields?: UpdateSiteRequestFields;
}
