/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */

export type UpdateSiteRequestDomainType = typeof UpdateSiteRequestDomainType[keyof typeof UpdateSiteRequestDomainType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSiteRequestDomainType = {
  DefaultDomain: 'DefaultDomain',
  SeparateDomain: 'SeparateDomain',
  BringYourDomain: 'BringYourDomain',
} as const;
