/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */

export type UpdateSiteRequestNewStatus = typeof UpdateSiteRequestNewStatus[keyof typeof UpdateSiteRequestNewStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSiteRequestNewStatus = {
  InCreation: 'InCreation',
  AwaitingProvision: 'AwaitingProvision',
  Created: 'Created',
} as const;
