/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * Returns a session ID cookie
 * @summary Gets a session from access token
 */
export const createSessionBody = zod.object({
  "accessToken": zod.string(),
  "refreshToken": zod.string(),
  "idToken": zod.string()
})

/**
 * Sends a mail with confirmation link for user signup
 * @summary Creates a confirmation mail with code for user signup
 */
export const createConfirmationBody = zod.object({
  "userID": zod.string(),
  "email": zod.string()
})

/**
 * Verifies provided confirmation code
 * @summary Verifies provided confirmation code
 */
export const verifyUserBody = zod.object({
  "code": zod.string()
})

export const verifyUserResponse = zod.object({
  "userID": zod.string()
})

/**
 * Verifies provided oauth2 id_token, creates a user and returns a session upon success
 * @summary Verifies provided oauth2 id_token
 */
export const verifyOauthTokenBody = zod.object({
  "idToken": zod.string()
})

