/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * Returns a client secret to create a checkout session for payment
 * @summary Gets a client secret to create a payment
 */
export const createPaymentBody = zod.object({
  "planID": zod.number(),
  "siteID": zod.number()
})

export const createPaymentResponse = zod.object({
  "clientSecret": zod.string().optional(),
  "subscriptionID": zod.string().optional()
})

/**
 * Returns a payment checkout session info
 * @summary Gets a payment checkout session info
 */
export const getPaymentStatusParams = zod.object({
  "id": zod.string()
})

export const getPaymentStatusResponse = zod.object({
  "status": zod.string(),
  "paymentStatus": zod.string(),
  "paymentIntentID": zod.string(),
  "paymentIntentStatus": zod.string()
})

/**
 * @summary Listens for webhook requests from stripe
 */
export const handleEventBody = zod.record(zod.string(), zod.any())

