import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Mulish } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { oauthConfig } from "@/shared/configs/oauth";
import axios from "axios";

const mulish = Mulish({
  weight: ["500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

axios.defaults.baseURL = "https://api.example.com";

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <GoogleOAuthProvider clientId={oauthConfig.clientId || ""}>
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
