import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Urbanist } from "next/font/google";
import { AppLayout } from "@/shared/layouts/app";
import { Header } from "@/widgets/header/ui";

const urbanist = Urbanist({
  weight: ["500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <AppLayout header={<Header />}>{children}</AppLayout>
      </body>
    </html>
  );
}
