/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Create a new template
 */
export const createTemplateBody = zod.object({
  "name": zod.string().describe('template\'s name'),
  "fields": zod.record(zod.string(), zod.any()).describe('json object with all widgets and fields of a site')
})

/**
 * Fetches new template sources and rebuilds them (if no templateName specified, fetches all)
 * @summary Update templates
 */
export const updateTemplatesBody = zod.object({
  "name": zod.string().optional().describe('template\'s name')
})

/**
 * Returns template info such as pages.json
 * @summary Gets template info
 */
export const getTemplateParams = zod.object({
  "id": zod.number()
})

export const getTemplateResponse = zod.object({
  "id": zod.number(),
  "templateName": zod.string(),
  "structure": zod.string().describe('url to pages.json file'),
  "styles": zod.string().describe('url to css file'),
  "preview": zod.string().describe('url to site\'s html for preview')
})

/**
 * Returns template list with info such as name, description, pages.json (url to s3)
 * @summary Gets template list with pagination
 */
export const listTemplatesBody = zod.object({
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

export const listTemplatesResponse = zod.object({
  "elements": zod.array(zod.object({
  "id": zod.number(),
  "templateName": zod.string(),
  "structure": zod.string().describe('url to pages.json file'),
  "styles": zod.string().describe('url to css file'),
  "preview": zod.string().describe('url to site\'s html for preview')
})),
  "page": zod.number(),
  "total": zod.number(),
  "hasNext": zod.boolean()
})

