/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Create a new template
 */
export const createTemplateBody = zod.object({
  "name": zod.string().describe('template\'s name'),
  "fields": zod.record(zod.string(), zod.any()).describe('json object with all widgets and fields of a site')
})

/**
 * Returns template info such as pages.json
 * @summary Gets template info
 */
export const getTemplateParams = zod.object({
  "id": zod.number()
})

export const getTemplateResponse = zod.object({
  "templateName": zod.string(),
  "structure": zod.string().describe('pages.json file')
})

