/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Site Creation API
 * API for creating user sites with templates
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Enrich some user provided info using AI
 */
export const enrichContentBody = zod.object({
  "content": zod.string()
})

export const enrichContentResponse = zod.object({
  "enriched": zod.string()
})

/**
 * @summary Upload a file for site static content
 */
export const fileUploadBody = zod.object({
  "file": zod.instanceof(File).optional(),
  "metadata": zod.record(zod.string(), zod.any()).optional().describe('json object with file metadata')
})

/**
 * Returns whether a domain is available or not
 * @summary Checks domain availability
 */
export const checkDomainParams = zod.object({
  "domain": zod.string()
})

export const checkDomainResponse = zod.object({
  "available": zod.boolean()
})

